name: Android CI

on: [push]

jobs:
  build-app:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [GitHubViewerApp, LocalDeviceNameResolution]
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Build ${{ matrix.app }}
        run: |
          cd android/${{ matrix.app }}
          ./gradlew build --stacktrace

  run-unit-tests:
    strategy:
      matrix:
        app: [GitHubViewerApp, LocalDeviceNameResolution]
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Run unit tests for ${{ matrix.app }}
        run: |
          cd android/${{ matrix.app }}
          ./gradlew test --info

  run-instrumented-tests:
    strategy:
      matrix:
        app: [GitHubViewerApp, LocalDeviceNameResolution]
    runs-on: macos-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Run instrumented tests for ${{ matrix.app }}
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: cd android/${{ matrix.app }} && ./gradlew connectedAndroidTest
