name: Android CI

on: [push]

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Build GitHubViewerApp
        run: |
          cd android/GitHubViewerApp
          ./gradlew build --stacktrace
      - name: Build LocalDeviceNameResolution app
        run: |
          cd android/LocalDeviceNameResolution
          ./gradlew build --stacktrace

  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Run unit tests for GitHubViewerApp
        run: |
          cd android/GitHubViewerApp
          ./gradlew test --info
      - name: Run unit tests for LocalDeviceNameResolution app
        run: |
          cd android/LocalDeviceNameResolution
          ./gradlew test --info

  run-instrumented-tests:
    runs-on: macos-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Run instrumented tests for GitHubViewerApp
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: cd android/GitHubViewerApp && ./gradlew connectedAndroidTest
      - name: Run instrumented tests for LocalDeviceNameResolution app
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: cd android/LocalDeviceNameResolution && ./gradlew connectedAndroidTest
